2018-12-06 14:25:22,043 ERROR: Exception on /user/chrisk0208 [GET] [in c:\users\rtcjk\appdata\local\programs\python\python36-32\lib\site-packages\flask\app.py:1760]
Traceback (most recent call last):
  File "c:\users\rtcjk\appdata\local\programs\python\python36-32\lib\site-packages\flask\app.py", line 2291, in wsgi_app
    response = self.full_dispatch_request()
  File "c:\users\rtcjk\appdata\local\programs\python\python36-32\lib\site-packages\flask\app.py", line 1814, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "c:\users\rtcjk\appdata\local\programs\python\python36-32\lib\site-packages\flask\app.py", line 1718, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "c:\users\rtcjk\appdata\local\programs\python\python36-32\lib\site-packages\flask\_compat.py", line 35, in reraise
    raise value
  File "c:\users\rtcjk\appdata\local\programs\python\python36-32\lib\site-packages\flask\app.py", line 1812, in full_dispatch_request
    rv = self.dispatch_request()
  File "c:\users\rtcjk\appdata\local\programs\python\python36-32\lib\site-packages\flask\app.py", line 1798, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "c:\users\rtcjk\appdata\local\programs\python\python36-32\lib\site-packages\flask_login\utils.py", line 261, in decorated_view
    return func(*args, **kwargs)
  File "C:\Projects\AppServer\FlaskApp\app\routes.py", line 92, in user
    page, app.config['POSTS_PER_PAGE'], False)
  File "c:\users\rtcjk\appdata\local\programs\python\python36-32\lib\site-packages\flask_sqlalchemy\__init__.py", line 485, in paginate
    if per_page < 0:
TypeError: '<' not supported between instances of 'UnboundField' and 'int'
2018-12-06 14:25:22,962 ERROR: Exception on /explore [GET] [in c:\users\rtcjk\appdata\local\programs\python\python36-32\lib\site-packages\flask\app.py:1760]
Traceback (most recent call last):
  File "c:\users\rtcjk\appdata\local\programs\python\python36-32\lib\site-packages\flask\app.py", line 2291, in wsgi_app
    response = self.full_dispatch_request()
  File "c:\users\rtcjk\appdata\local\programs\python\python36-32\lib\site-packages\flask\app.py", line 1814, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "c:\users\rtcjk\appdata\local\programs\python\python36-32\lib\site-packages\flask\app.py", line 1718, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "c:\users\rtcjk\appdata\local\programs\python\python36-32\lib\site-packages\flask\_compat.py", line 35, in reraise
    raise value
  File "c:\users\rtcjk\appdata\local\programs\python\python36-32\lib\site-packages\flask\app.py", line 1812, in full_dispatch_request
    rv = self.dispatch_request()
  File "c:\users\rtcjk\appdata\local\programs\python\python36-32\lib\site-packages\flask\app.py", line 1798, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "c:\users\rtcjk\appdata\local\programs\python\python36-32\lib\site-packages\flask_login\utils.py", line 261, in decorated_view
    return func(*args, **kwargs)
  File "C:\Projects\AppServer\FlaskApp\app\routes.py", line 156, in explore
    page, app.config['POSTS_PER_PAGE'], False)
  File "c:\users\rtcjk\appdata\local\programs\python\python36-32\lib\site-packages\flask_sqlalchemy\__init__.py", line 485, in paginate
    if per_page < 0:
TypeError: '<' not supported between instances of 'UnboundField' and 'int'
2018-12-06 14:26:02,511 INFO: FlaskApp [in C:\Projects\AppServer\FlaskApp\app\__init__.py:43]
2018-12-06 14:26:41,844 INFO: FlaskApp [in C:\Projects\AppServer\FlaskApp\app\__init__.py:43]
2018-12-06 14:26:43,836 ERROR: Exception on /index [POST] [in c:\users\rtcjk\appdata\local\programs\python\python36-32\lib\site-packages\flask\app.py:1760]
Traceback (most recent call last):
  File "c:\users\rtcjk\appdata\local\programs\python\python36-32\lib\site-packages\flask\app.py", line 2291, in wsgi_app
    response = self.full_dispatch_request()
  File "c:\users\rtcjk\appdata\local\programs\python\python36-32\lib\site-packages\flask\app.py", line 1814, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "c:\users\rtcjk\appdata\local\programs\python\python36-32\lib\site-packages\flask\app.py", line 1718, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "c:\users\rtcjk\appdata\local\programs\python\python36-32\lib\site-packages\flask\_compat.py", line 35, in reraise
    raise value
  File "c:\users\rtcjk\appdata\local\programs\python\python36-32\lib\site-packages\flask\app.py", line 1812, in full_dispatch_request
    rv = self.dispatch_request()
  File "c:\users\rtcjk\appdata\local\programs\python\python36-32\lib\site-packages\flask\app.py", line 1798, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "c:\users\rtcjk\appdata\local\programs\python\python36-32\lib\site-packages\flask_login\utils.py", line 261, in decorated_view
    return func(*args, **kwargs)
  File "C:\Projects\AppServer\FlaskApp\app\routes.py", line 25, in index
    if pageForm.validate_on_submit():
  File "c:\users\rtcjk\appdata\local\programs\python\python36-32\lib\site-packages\flask_wtf\form.py", line 101, in validate_on_submit
    return self.is_submitted() and self.validate()
  File "c:\users\rtcjk\appdata\local\programs\python\python36-32\lib\site-packages\wtforms\form.py", line 310, in validate
    return super(Form, self).validate(extra)
  File "c:\users\rtcjk\appdata\local\programs\python\python36-32\lib\site-packages\wtforms\form.py", line 152, in validate
    if not field.validate(self, extra):
  File "c:\users\rtcjk\appdata\local\programs\python\python36-32\lib\site-packages\wtforms\fields\core.py", line 195, in validate
    self.pre_validate(form)
  File "c:\users\rtcjk\appdata\local\programs\python\python36-32\lib\site-packages\wtforms\fields\core.py", line 471, in pre_validate
    for v, _ in self.choices:
TypeError: 'NoneType' object is not iterable
2018-12-06 14:28:33,841 INFO: FlaskApp [in C:\Projects\AppServer\FlaskApp\app\__init__.py:43]
2018-12-06 14:28:40,856 ERROR: Exception on /index [POST] [in c:\users\rtcjk\appdata\local\programs\python\python36-32\lib\site-packages\flask\app.py:1760]
Traceback (most recent call last):
  File "c:\users\rtcjk\appdata\local\programs\python\python36-32\lib\site-packages\flask\app.py", line 2291, in wsgi_app
    response = self.full_dispatch_request()
  File "c:\users\rtcjk\appdata\local\programs\python\python36-32\lib\site-packages\flask\app.py", line 1814, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "c:\users\rtcjk\appdata\local\programs\python\python36-32\lib\site-packages\flask\app.py", line 1718, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "c:\users\rtcjk\appdata\local\programs\python\python36-32\lib\site-packages\flask\_compat.py", line 35, in reraise
    raise value
  File "c:\users\rtcjk\appdata\local\programs\python\python36-32\lib\site-packages\flask\app.py", line 1812, in full_dispatch_request
    rv = self.dispatch_request()
  File "c:\users\rtcjk\appdata\local\programs\python\python36-32\lib\site-packages\flask\app.py", line 1798, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "c:\users\rtcjk\appdata\local\programs\python\python36-32\lib\site-packages\flask_login\utils.py", line 261, in decorated_view
    return func(*args, **kwargs)
  File "C:\Projects\AppServer\FlaskApp\app\routes.py", line 25, in index
    if pageForm.validate_on_submit():
  File "c:\users\rtcjk\appdata\local\programs\python\python36-32\lib\site-packages\flask_wtf\form.py", line 101, in validate_on_submit
    return self.is_submitted() and self.validate()
  File "c:\users\rtcjk\appdata\local\programs\python\python36-32\lib\site-packages\wtforms\form.py", line 310, in validate
    return super(Form, self).validate(extra)
  File "c:\users\rtcjk\appdata\local\programs\python\python36-32\lib\site-packages\wtforms\form.py", line 152, in validate
    if not field.validate(self, extra):
  File "c:\users\rtcjk\appdata\local\programs\python\python36-32\lib\site-packages\wtforms\fields\core.py", line 195, in validate
    self.pre_validate(form)
  File "c:\users\rtcjk\appdata\local\programs\python\python36-32\lib\site-packages\wtforms\fields\core.py", line 471, in pre_validate
    for v, _ in self.choices:
TypeError: 'int' object is not iterable
