2018-12-06 14:28:44,468 ERROR: Exception on /index [POST] [in c:\users\rtcjk\appdata\local\programs\python\python36-32\lib\site-packages\flask\app.py:1760]
Traceback (most recent call last):
  File "c:\users\rtcjk\appdata\local\programs\python\python36-32\lib\site-packages\flask\app.py", line 2291, in wsgi_app
    response = self.full_dispatch_request()
  File "c:\users\rtcjk\appdata\local\programs\python\python36-32\lib\site-packages\flask\app.py", line 1814, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "c:\users\rtcjk\appdata\local\programs\python\python36-32\lib\site-packages\flask\app.py", line 1718, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "c:\users\rtcjk\appdata\local\programs\python\python36-32\lib\site-packages\flask\_compat.py", line 35, in reraise
    raise value
  File "c:\users\rtcjk\appdata\local\programs\python\python36-32\lib\site-packages\flask\app.py", line 1812, in full_dispatch_request
    rv = self.dispatch_request()
  File "c:\users\rtcjk\appdata\local\programs\python\python36-32\lib\site-packages\flask\app.py", line 1798, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "c:\users\rtcjk\appdata\local\programs\python\python36-32\lib\site-packages\flask_login\utils.py", line 261, in decorated_view
    return func(*args, **kwargs)
  File "C:\Projects\AppServer\FlaskApp\app\routes.py", line 25, in index
    if pageForm.validate_on_submit():
  File "c:\users\rtcjk\appdata\local\programs\python\python36-32\lib\site-packages\flask_wtf\form.py", line 101, in validate_on_submit
    return self.is_submitted() and self.validate()
  File "c:\users\rtcjk\appdata\local\programs\python\python36-32\lib\site-packages\wtforms\form.py", line 310, in validate
    return super(Form, self).validate(extra)
  File "c:\users\rtcjk\appdata\local\programs\python\python36-32\lib\site-packages\wtforms\form.py", line 152, in validate
    if not field.validate(self, extra):
  File "c:\users\rtcjk\appdata\local\programs\python\python36-32\lib\site-packages\wtforms\fields\core.py", line 195, in validate
    self.pre_validate(form)
  File "c:\users\rtcjk\appdata\local\programs\python\python36-32\lib\site-packages\wtforms\fields\core.py", line 471, in pre_validate
    for v, _ in self.choices:
TypeError: 'int' object is not iterable
2018-12-06 14:28:49,748 ERROR: Exception on /index [POST] [in c:\users\rtcjk\appdata\local\programs\python\python36-32\lib\site-packages\flask\app.py:1760]
Traceback (most recent call last):
  File "c:\users\rtcjk\appdata\local\programs\python\python36-32\lib\site-packages\flask\app.py", line 2291, in wsgi_app
    response = self.full_dispatch_request()
  File "c:\users\rtcjk\appdata\local\programs\python\python36-32\lib\site-packages\flask\app.py", line 1814, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "c:\users\rtcjk\appdata\local\programs\python\python36-32\lib\site-packages\flask\app.py", line 1718, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "c:\users\rtcjk\appdata\local\programs\python\python36-32\lib\site-packages\flask\_compat.py", line 35, in reraise
    raise value
  File "c:\users\rtcjk\appdata\local\programs\python\python36-32\lib\site-packages\flask\app.py", line 1812, in full_dispatch_request
    rv = self.dispatch_request()
  File "c:\users\rtcjk\appdata\local\programs\python\python36-32\lib\site-packages\flask\app.py", line 1798, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "c:\users\rtcjk\appdata\local\programs\python\python36-32\lib\site-packages\flask_login\utils.py", line 261, in decorated_view
    return func(*args, **kwargs)
  File "C:\Projects\AppServer\FlaskApp\app\routes.py", line 25, in index
    if pageForm.validate_on_submit():
  File "c:\users\rtcjk\appdata\local\programs\python\python36-32\lib\site-packages\flask_wtf\form.py", line 101, in validate_on_submit
    return self.is_submitted() and self.validate()
  File "c:\users\rtcjk\appdata\local\programs\python\python36-32\lib\site-packages\wtforms\form.py", line 310, in validate
    return super(Form, self).validate(extra)
  File "c:\users\rtcjk\appdata\local\programs\python\python36-32\lib\site-packages\wtforms\form.py", line 152, in validate
    if not field.validate(self, extra):
  File "c:\users\rtcjk\appdata\local\programs\python\python36-32\lib\site-packages\wtforms\fields\core.py", line 195, in validate
    self.pre_validate(form)
  File "c:\users\rtcjk\appdata\local\programs\python\python36-32\lib\site-packages\wtforms\fields\core.py", line 471, in pre_validate
    for v, _ in self.choices:
TypeError: 'int' object is not iterable
2018-12-06 14:31:38,632 INFO: FlaskApp [in C:\Projects\AppServer\FlaskApp\app\__init__.py:43]
2018-12-06 14:31:50,160 INFO: FlaskApp [in C:\Projects\AppServer\FlaskApp\app\__init__.py:43]
2018-12-06 14:32:23,861 INFO: FlaskApp [in C:\Projects\AppServer\FlaskApp\app\__init__.py:43]
2018-12-06 14:32:40,076 INFO: FlaskApp [in C:\Projects\AppServer\FlaskApp\app\__init__.py:43]
2018-12-06 14:32:59,146 INFO: FlaskApp [in C:\Projects\AppServer\FlaskApp\app\__init__.py:43]
2018-12-06 14:33:13,058 INFO: FlaskApp [in C:\Projects\AppServer\FlaskApp\app\__init__.py:43]
2018-12-06 14:33:31,137 INFO: FlaskApp [in C:\Projects\AppServer\FlaskApp\app\__init__.py:43]
2018-12-06 14:34:02,155 INFO: FlaskApp [in C:\Projects\AppServer\FlaskApp\app\__init__.py:43]
2018-12-06 14:35:00,761 INFO: FlaskApp [in C:\Projects\AppServer\FlaskApp\app\__init__.py:43]
2018-12-06 14:35:17,209 INFO: FlaskApp [in C:\Projects\AppServer\FlaskApp\app\__init__.py:43]
2018-12-06 14:35:40,958 INFO: FlaskApp [in C:\Projects\AppServer\FlaskApp\app\__init__.py:43]
2018-12-06 14:36:00,296 INFO: FlaskApp [in C:\Projects\AppServer\FlaskApp\app\__init__.py:43]
2018-12-06 14:36:30,586 INFO: FlaskApp [in C:\Projects\AppServer\FlaskApp\app\__init__.py:43]
2018-12-06 14:36:52,397 INFO: FlaskApp [in C:\Projects\AppServer\FlaskApp\app\__init__.py:43]
2018-12-06 14:37:25,588 INFO: FlaskApp [in C:\Projects\AppServer\FlaskApp\app\__init__.py:43]
2018-12-06 14:37:41,188 INFO: FlaskApp [in C:\Projects\AppServer\FlaskApp\app\__init__.py:43]
2018-12-06 14:39:03,188 INFO: FlaskApp [in C:\Projects\AppServer\FlaskApp\app\__init__.py:43]
2018-12-06 14:39:56,217 INFO: FlaskApp [in C:\Projects\AppServer\FlaskApp\app\__init__.py:43]
2018-12-06 14:43:45,010 INFO: FlaskApp [in C:\Projects\AppServer\FlaskApp\app\__init__.py:43]
2018-12-06 14:46:05,193 INFO: FlaskApp [in C:\Projects\AppServer\FlaskApp\app\__init__.py:43]
