2018-12-17 10:37:10,648 ERROR: Exception on /reset_password_request [POST] [in c:\users\rtcjk\appdata\local\programs\python\python36-32\lib\site-packages\flask\app.py:1760]
Traceback (most recent call last):
  File "c:\users\rtcjk\appdata\local\programs\python\python36-32\lib\site-packages\flask\app.py", line 2291, in wsgi_app
    response = self.full_dispatch_request()
  File "c:\users\rtcjk\appdata\local\programs\python\python36-32\lib\site-packages\flask\app.py", line 1814, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "c:\users\rtcjk\appdata\local\programs\python\python36-32\lib\site-packages\flask\app.py", line 1718, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "c:\users\rtcjk\appdata\local\programs\python\python36-32\lib\site-packages\flask\_compat.py", line 35, in reraise
    raise value
  File "c:\users\rtcjk\appdata\local\programs\python\python36-32\lib\site-packages\flask\app.py", line 1812, in full_dispatch_request
    rv = self.dispatch_request()
  File "c:\users\rtcjk\appdata\local\programs\python\python36-32\lib\site-packages\flask\app.py", line 1798, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "C:\Projects\AppServer\FlaskApp\app\routes.py", line 178, in reset_password_request
    send_password_reset_email(user)
  File "C:\Projects\AppServer\FlaskApp\app\email.py", line 21, in send_password_reset_email
    user=user, token=token))
  File "C:\Projects\AppServer\FlaskApp\app\email.py", line 32, in send_email
    Thread(target=send_async_email, args=(app, msg)).start()
NameError: name 'send_async_email' is not defined
2018-12-17 10:39:07,991 INFO: FlaskApp [in C:\Projects\AppServer\FlaskApp\app\__init__.py:45]
